//go:build gcp_differential

package gcpdifferential

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// bqsqlBacklogFile is the committed frontier document the BigQuery SQL replay
// emits: every corpus case the emulator does not yet match, with its declared
// expectation and the real-GCP-vs-emulator evidence the replay computed. The
// per-query match/mismatch table only exists in verbose test logs; this makes
// the frontier a tracked, reviewable artifact. Like report.{json,md} it is
// regenerated by each replay (the path is force-included in .gitignore).
const bqsqlBacklogFile = "backlog.md"

// writeBQSQLBacklog renders the gap/bug frontier to dir/backlog.md from the
// replay's per-case results and the open divergences it triaged. It is
// deterministic: cases are emitted in ID order and evidence in diff order.
func writeBQSQLBacklog(t interface {
	Helper()
	Errorf(format string, args ...any)
}, dir string, results []bqsqlResult, openByOp map[string][]Divergence, pending []string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Errorf("create BigQuery SQL backlog dir: %v", err)
		return
	}
	if err := os.WriteFile(filepath.Join(dir, bqsqlBacklogFile), []byte(renderBQSQLBacklog(results, openByOp, pending)), 0o644); err != nil {
		t.Errorf("write BigQuery SQL backlog: %v", err)
	}
}

// renderBQSQLBacklog builds the backlog markdown. Only the gap/bug cases are
// listed in full (they are the actionable frontier); match cases are counted in
// a per-class summary so the document stays focused. A gap/bug case with no
// open divergence has started matching and is flagged as a stale expectation.
func renderBQSQLBacklog(results []bqsqlResult, openByOp map[string][]Divergence, pending []string) string {
	sorted := append([]bqsqlResult(nil), results...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Case.ID < sorted[j].Case.ID })

	counts := map[BQSQLExpect]int{}
	classTotals := map[string]map[BQSQLExpect]int{}
	for _, r := range sorted {
		counts[r.Case.Expect]++
		if classTotals[r.Case.Class] == nil {
			classTotals[r.Case.Class] = map[BQSQLExpect]int{}
		}
		classTotals[r.Case.Class][r.Case.Expect]++
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# BigQuery SQL differential frontier (gap/bug backlog)\n\n")
	fmt.Fprintf(&b, "Generated by `TestReplayBQSQL` — do not edit by hand. It lists every corpus\n")
	fmt.Fprintf(&b, "case the emulator does not yet match, with its declared expectation and the\n")
	fmt.Fprintf(&b, "real-GCP-vs-emulator evidence the replay computed. Regenerate it with\n")
	fmt.Fprintf(&b, "`make test-gcp-differential-bigquery`.\n\n")
	fmt.Fprintf(&b, "Summary: **%d match, %d gap, %d bug** (%d cases).\n\n",
		counts[BQSQLMatch], counts[BQSQLGap], counts[BQSQLBug], len(sorted))

	// Per-class summary.
	fmt.Fprintf(&b, "| class | match | gap | bug |\n| --- | ---: | ---: | ---: |\n")
	for _, class := range sortedClassKeys(classTotals) {
		c := classTotals[class]
		fmt.Fprintf(&b, "| %s | %d | %d | %d |\n", mdEscape(class), c[BQSQLMatch], c[BQSQLGap], c[BQSQLBug])
	}
	fmt.Fprintf(&b, "\n")

	// Frontier index: every gap/bug case with its replay outcome.
	fmt.Fprintf(&b, "## Frontier index\n\n")
	fmt.Fprintf(&b, "| ID | class | expect | HTTP | divergences | state |\n| --- | --- | --- | ---: | ---: | --- |\n")
	var frontier []bqsqlResult
	for _, r := range sorted {
		if r.Case.Expect == BQSQLMatch {
			continue
		}
		frontier = append(frontier, r)
		open := len(openByOp[bqsqlOp(r.Case)])
		state := "diverges (expected)"
		if open == 0 {
			state = "**matches now — stale expectation**"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %d | %d | %s |\n",
			mdEscape(r.Case.ID), mdEscape(r.Case.Class), mdEscape(string(r.Case.Expect)), r.Status, open, state)
	}
	fmt.Fprintf(&b, "\n")

	// Per-case evidence.
	fmt.Fprintf(&b, "## Evidence\n\n")
	for _, r := range frontier {
		op := bqsqlOp(r.Case)
		open := openByOp[op]
		fmt.Fprintf(&b, "### %s — %s (%s)\n\n", mdEscape(r.Case.ID), mdEscape(string(r.Case.Expect)), mdEscape(r.Case.Class))
		fmt.Fprintf(&b, "SQL: `%s`\n\n", mdEscape(strings.ReplaceAll(r.Case.SQL, "`", "'")))
		fmt.Fprintf(&b, "HTTP %d, %d accepted divergence(s) triaged.\n\n", r.Status, r.Accepted)
		if len(open) == 0 {
			fmt.Fprintf(&b, "The emulator now matches real GCP for this case; the declared `%s` expectation is stale and should be updated to `match`.\n\n", r.Case.Expect)
			continue
		}
		fmt.Fprintf(&b, "| kind | location | real GCP | emulator |\n| --- | --- | --- | --- |\n")
		for _, d := range open {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				mdEscape(d.Kind), mdEscape(d.Location), mdEscape(d.Expected), mdEscape(d.Actual))
		}
		fmt.Fprintf(&b, "\n")
	}

	if len(pending) > 0 {
		p := append([]string(nil), pending...)
		sort.Strings(p)
		fmt.Fprintf(&b, "## Pending recording\n\n%d case(s) have no committed golden: %s\n",
			len(p), strings.Join(p, ", "))
	}
	return b.String()
}

// bqsqlOp is the scenario Op id a corpus case maps to.
func bqsqlOp(c BQSQLCase) string { return "bqsql_" + c.ID }

func sortedClassKeys[M ~map[string]map[BQSQLExpect]int](m M) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
